from tests.st.compiler.fallback.control_flow.test_fallback_000_single_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_001_single_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_002_single_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_010_if_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_011_if_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_012_if_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_020_while_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_021_while_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_022_while_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_030_for_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_031_for_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_100_if_after_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_101_if_after_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_110_if_after_if_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_111_if_after_if_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_112_if_after_if_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_120_if_after_while_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_121_if_after_while_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_122_if_after_while_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_130_if_after_for_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_131_if_after_for_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_132_if_after_for_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_200_while_after_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_201_while_after_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_202_while_after_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_210_while_after_if_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_211_while_after_if_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_212_while_after_if_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_220_while_after_while_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_221_while_after_while_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_222_while_after_while_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_230_while_after_for_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_231_while_after_for_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_232_while_after_for_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_300_for_after_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_301_for_after_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_302_for_after_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_310_for_after_if_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_311_for_after_if_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_320_for_after_while_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_321_for_after_while_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_322_for_after_while_in_for import *
from tests.st.compiler.fallback.control_flow.test_fallback_330_for_after_for_in_if import *
from tests.st.compiler.fallback.control_flow.test_fallback_331_for_after_for_in_while import *
from tests.st.compiler.fallback.control_flow.test_fallback_332_for_after_for_in_for import *
