# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ==============================================================================
pos_dir: 'data/rt-polaritydata/rt-polarity.pos'
neg_dir: 'data/rt-polaritydata/rt-polarity.neg'
num_epochs: 10
lstm_num_epochs: 15
batch_size: 64
cell: 'gru'
ckpt_folder_path: './ckpt'
preprocess_path: './preprocess'
preprocess: 'false'
data_root: './data/'
lr: 0.001  # 1e-3
lstm_lr_init: 0.002  # 2e-3
lstm_lr_end: 0.0005  # 5e-4
lstm_lr_max: 0.003  # 3e-3
lstm_lr_warm_up_epochs: 2
lstm_lr_adjust_epochs: 9
emb_path: './word2vec'
embed_size: 300
save_checkpoint_steps: 149
keep_checkpoint_max: 10
ckpt_path: ''

# Export related
ckpt_file: ''
file_name: 'textrcnn'
file_format: "MINDIR"

# postprocess and result_path related
pre_result_path: "./preprocess_Result"
label_path: "./preprocess_Result/label_ids.npy"
result_path: "./result_Files"

---

# Help description for each configuration
# ModelArts related
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of the input data."
output_path: "The location of the output file."
device_target: "Running platform, choose from Ascend, GPU or CPU, and default is Ascend."
enable_profiling: 'Whether enable profiling while training, default: False'
# Export related
ckpt_file: "textrcnn ckpt file."
file_name: "textrcnn output file name."
file_format: "file format, choose from MINDIR or AIR"

---
file_format: ["AIR", "MINDIR"]
device_target: ["Ascend"]