package:
  name: mindspore-ascend
  version: "1.5.0rc1"

build:
  number: 0
  rpaths:
    - /usr/local/Ascend/nnae/latest/fwkacllib/lib64
    - /usr/local/Ascend/ascend-toolkit/latest/fwkacllib/lib64
    - /usr/local/Ascend/fwkacllib/lib64
    - /usr/local/Ascend/nnae/latest/fwkacllib/lib64/plugin/opskernel
    - /usr/local/Ascend/ascend-toolkit/latest/fwkacllib/lib64/plugin/opskernel
    - /usr/local/Ascend/fwkacllib/lib64/plugin/opskernel
    - /usr/local/Ascend/opp/op_impl/built-in/ai_core/tbe/op_tiling
    - /usr/local/Ascend/nnae/latest/opp/op_impl/built-in/ai_core/tbe/op_tiling
    - /usr/local/Ascend/ascend-toolkit/latest/opp/op_impl/built-in/ai_core/tbe/op_tiling

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.17.0
    - protobuf >=3.13.0
    - asttokens >=1.1.13
    - pillow >=6.2.0
    - scipy >=1.5.2
    - cffi >=1.12.3
    - wheel >=0.32.0
    - decorator >=4.4.0
    - setuptools >=40.8.0
    - astunparse >=1.6.3
    - packaging >=20.0
    - psutil >=5.7.0

about:
  home: https://www.mindspore.cn/
  license: Apache 2.0
  summary: MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios.
