# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "face_detect_dataset"

# ==============================================================================
# train options
run_platform: "Ascend" # choices in ("Ascend", "CPU", "GPU")
mindrecord_path: ""    # change to your own path of train data
pretrained: ""         # if you have pretrained backbone, set the path of pretrained_ckpt
use_loss_scale: True

# default options
batch_size: 64
warmup_lr: 0.0004
lr_rates: [0.002, 0.004, 0.002, 0.0008, 0.0004, 0.0002, 0.00008, 0.00004, 0.000004]
lr_steps: [1000, 10000, 40000, 60000, 80000, 100000, 130000, 160000, 190000]
gamma: 0.5
weight_decay: 0.0005
momentum: 0.5
max_epoch: 2500

log_interval: 10
ckpt_path: "./output"
ckpt_interval: 1000
result_path: "./results"

input_shape: [768, 448]
jitter: 0.3
flip: 0.5
hue: 0.1
sat: 1.5
val: 1.5
num_classes: 1
anchors: [[3, 4],
          [5, 6],
          [7, 9],
          [10, 13],
          [15, 19],
          [21, 26],
          [28, 36],
          [38, 49],
          [54, 71],
          [77, 102],
          [122, 162],
          [207, 268]]

anchors_mask: [[8, 9, 10, 11], [4, 5, 6, 7], [0, 1, 2, 3]]

conf_thresh: 0.1
nms_thresh: 0.45

#export
file_name: "FaceDetection"
file_format: "AIR"

#310 infer
preprocess_path: ""
save_output_path: ""
data_dir: ""

---

# Help description for each configuration
# train options
run_platform: "run platform, support Ascend and CPU."
mindrecord_path: "dataset path, e.g. /home/data.mindrecord"
pretrained: "pretrained model to load"
local_rank: "current rank to support distributed"
use_loss_scale: "Whether use dynamic loss scale, default is True."
