/**
 * Copyright 2021 Huawei Technologies Co., Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace mindspore {
namespace lite {
#ifdef MS_COMPILE_IOS
// populate
extern void _PrimitiveType_MulFusionSCHEMA_CUR();
extern void _PrimitiveType_NonMaxSuppressionSCHEMA_CUR();
extern void _PrimitiveType_TensorListStackSCHEMA_CUR();
extern void _PrimitiveType_EltwiseSCHEMA_CUR();
extern void _PrimitiveType_AssignSCHEMA_CUR();
extern void _PrimitiveType_CropSCHEMA_CUR();
extern void _PrimitiveType_BatchNormSCHEMA_CUR();
extern void _PrimitiveType_NonZeroSCHEMA_CUR();
extern void _PrimitiveType_AddNSCHEMA_CUR();
extern void _PrimitiveType_MergeSCHEMA_CUR();
extern void _PrimitiveType_AbsSCHEMA_CUR();
extern void _PrimitiveType_CosSCHEMA_CUR();
extern void _PrimitiveType_SinSCHEMA_CUR();
extern void _PrimitiveType_LogSCHEMA_CUR();
extern void _PrimitiveType_NegSCHEMA_CUR();
extern void _PrimitiveType_NegGradSCHEMA_CUR();
extern void _PrimitiveType_LogGradSCHEMA_CUR();
extern void _PrimitiveType_SqrtSCHEMA_CUR();
extern void _PrimitiveType_SquareSCHEMA_CUR();
extern void _PrimitiveType_RsqrtSCHEMA_CUR();
extern void _PrimitiveType_LogicalNotSCHEMA_CUR();
extern void _PrimitiveType_FloorSCHEMA_CUR();
extern void _PrimitiveType_CeilSCHEMA_CUR();
extern void _PrimitiveType_RoundSCHEMA_CUR();
extern void _PrimitiveType_ReciprocalSCHEMA_CUR();
extern void _PrimitiveType_AssignAddSCHEMA_CUR();
extern void _PrimitiveType_UniqueSCHEMA_CUR();
extern void _PrimitiveType_IsFiniteSCHEMA_CUR();
extern void _PrimitiveType_TileFusionSCHEMA_CUR();
extern void _PrimitiveType_BinaryCrossEntropyGradSCHEMA_CUR();
extern void _PrimitiveType_StridedSliceSCHEMA_CUR();
extern void _PrimitiveType_L2NormalizeFusionSCHEMA_CUR();
extern void _PrimitiveType_RangeSCHEMA_CUR();
extern void _PrimitiveType_SizeSCHEMA_CUR();
extern void _PrimitiveType_CropAndResizeSCHEMA_CUR();
extern void _PrimitiveType_QuantDTypeCastSCHEMA_CUR();
extern void _PrimitiveType_InstanceNormSCHEMA_CUR();
extern void _PrimitiveType_AddFusionSCHEMA_CUR();
extern void _PrimitiveType_Conv2dTransposeFusionSCHEMA_CUR();
extern void _PrimitiveType_PowFusionSCHEMA_CUR();
extern void _PrimitiveType_ReverseV2SCHEMA_CUR();
extern void _PrimitiveType_BiasAddSCHEMA_CUR();
extern void _PrimitiveType_TensorListReserveSCHEMA_CUR();
extern void _PrimitiveType_SpliceSCHEMA_CUR();
extern void _PrimitiveType_MatMulSCHEMA_CUR();
extern void _PrimitiveType_ErfSCHEMA_CUR();
extern void _PrimitiveType_MinimumGradSCHEMA_CUR();
extern void _PrimitiveType_MaximumGradSCHEMA_CUR();
extern void _PrimitiveType_RealDivSCHEMA_CUR();
extern void _PrimitiveType_LogicalAndSCHEMA_CUR();
extern void _PrimitiveType_LogicalOrSCHEMA_CUR();
extern void _PrimitiveType_EqualSCHEMA_CUR();
extern void _PrimitiveType_NotEqualSCHEMA_CUR();
extern void _PrimitiveType_LessSCHEMA_CUR();
extern void _PrimitiveType_LessEqualSCHEMA_CUR();
extern void _PrimitiveType_GreaterSCHEMA_CUR();
extern void _PrimitiveType_GreaterEqualSCHEMA_CUR();
extern void _PrimitiveType_MaximumSCHEMA_CUR();
extern void _PrimitiveType_MinimumSCHEMA_CUR();
extern void _PrimitiveType_FloorDivSCHEMA_CUR();
extern void _PrimitiveType_FloorModSCHEMA_CUR();
extern void _PrimitiveType_ModSCHEMA_CUR();
extern void _PrimitiveType_SquaredDifferenceSCHEMA_CUR();
extern void _PrimitiveType_OneHotSCHEMA_CUR();
extern void _PrimitiveType_WhileSCHEMA_CUR();
extern void _PrimitiveType_ScatterNdSCHEMA_CUR();
extern void _PrimitiveType_DepthToSpaceSCHEMA_CUR();
extern void _PrimitiveType_GatherSCHEMA_CUR();
extern void _PrimitiveType_AssertSCHEMA_CUR();
extern void _PrimitiveType_InvertPermutationSCHEMA_CUR();
extern void _PrimitiveType_OnesLikeSCHEMA_CUR();
extern void _PrimitiveType_ConcatSCHEMA_CUR();
extern void _PrimitiveType_ScaleFusionSCHEMA_CUR();
extern void _PrimitiveType_HashtableLookupSCHEMA_CUR();
extern void _PrimitiveType_StackSCHEMA_CUR();
extern void _PrimitiveType_ShapeSCHEMA_CUR();
extern void _PrimitiveType_SparseToDenseSCHEMA_CUR();
extern void _PrimitiveType_TensorListFromTensorSCHEMA_CUR();
extern void _PrimitiveType_ReverseSequenceSCHEMA_CUR();
extern void _PrimitiveType_UnsqueezeSCHEMA_CUR();
extern void _PrimitiveType_FlattenSCHEMA_CUR();
extern void _PrimitiveType_ArgMinFusionSCHEMA_CUR();
extern void _PrimitiveType_SpaceToBatchSCHEMA_CUR();
extern void _PrimitiveType_UnstackSCHEMA_CUR();
extern void _PrimitiveType_BroadcastToSCHEMA_CUR();
extern void _PrimitiveType_SelectSCHEMA_CUR();
extern void _PrimitiveType_LinSpaceSCHEMA_CUR();
extern void _PrimitiveType_BiasAddGradSCHEMA_CUR();
extern void _PrimitiveType_LayerNormFusionSCHEMA_CUR();
extern void _PrimitiveType_EmbeddingLookupFusionSCHEMA_CUR();
extern void _PrimitiveType_CustomExtractFeaturesSCHEMA_CUR();
extern void _PrimitiveType_ResizeSCHEMA_CUR();
extern void _PrimitiveType_AdamSCHEMA_CUR();
extern void _PrimitiveType_ExpandDimsSCHEMA_CUR();
extern void _PrimitiveType_IfSCHEMA_CUR();
extern void _PrimitiveType_SoftmaxSCHEMA_CUR();
extern void _PrimitiveType_BatchToSpaceSCHEMA_CUR();
extern void _PrimitiveType_BatchToSpaceNDSCHEMA_CUR();
extern void _PrimitiveType_UniformRealSCHEMA_CUR();
extern void _PrimitiveType_DetectionPostProcessSCHEMA_CUR();
extern void _PrimitiveType_GatherNdSCHEMA_CUR();
extern void _PrimitiveType_GRUSCHEMA_CUR();
extern void _PrimitiveType_CustomNormalizeSCHEMA_CUR();
extern void _PrimitiveType_AdderFusionSCHEMA_CUR();
extern void _PrimitiveType_RandomStandardNormalSCHEMA_CUR();
extern void _PrimitiveType_FusedBatchNormSCHEMA_CUR();
extern void _PrimitiveType_AvgPoolFusionSCHEMA_CUR();
extern void _PrimitiveType_MaxPoolFusionSCHEMA_CUR();
extern void _PrimitiveType_ArgMaxFusionSCHEMA_CUR();
extern void _PrimitiveType_ExpFusionSCHEMA_CUR();
extern void _PrimitiveType_LayerNormGradSCHEMA_CUR();
extern void _PrimitiveType_AudioSpectrogramSCHEMA_CUR();
extern void _PrimitiveType_SpaceToBatchNDSCHEMA_CUR();
extern void _PrimitiveType_ROIPoolingSCHEMA_CUR();
extern void _PrimitiveType_PReLUFusionSCHEMA_CUR();
extern void _PrimitiveType_WhereSCHEMA_CUR();
extern void _PrimitiveType_SparseSoftmaxCrossEntropyWithLogitsSCHEMA_CUR();
extern void _PrimitiveType_PartialFusionSCHEMA_CUR();
extern void _PrimitiveType_SubFusionSCHEMA_CUR();
extern void _PrimitiveType_DivFusionSCHEMA_CUR();
extern void _PrimitiveType_MfccSCHEMA_CUR();
extern void _PrimitiveType_SplitSCHEMA_CUR();
extern void _PrimitiveType_ActivationSCHEMA_CUR();
extern void _PrimitiveType_TopKFusionSCHEMA_CUR();
extern void _PrimitiveType_CastSCHEMA_CUR();
extern void _PrimitiveType_StridedSliceGradSCHEMA_CUR();
extern void _PrimitiveType_SliceFusionSCHEMA_CUR();
extern void _PrimitiveType_TransposeSCHEMA_CUR();
extern void _PrimitiveType_ReduceFusionSCHEMA_CUR();
extern void _PrimitiveType_FullConnectionSCHEMA_CUR();
extern void _PrimitiveType_LshProjectionSCHEMA_CUR();
extern void _PrimitiveType_SkipGramSCHEMA_CUR();
extern void _PrimitiveType_SqueezeSCHEMA_CUR();
extern void _PrimitiveType_ActivationGradSCHEMA_CUR();
extern void _PrimitiveType_SwitchSCHEMA_CUR();
extern void _PrimitiveType_LSTMSCHEMA_CUR();
extern void _PrimitiveType_BinaryCrossEntropySCHEMA_CUR();
extern void _PrimitiveType_EluSCHEMA_CUR();
extern void _PrimitiveType_Conv2DFusionSCHEMA_CUR();
extern void _PrimitiveType_TensorListGetItemSCHEMA_CUR();
extern void _PrimitiveType_LRNSCHEMA_CUR();
extern void _PrimitiveType_ReshapeSCHEMA_CUR();
extern void _PrimitiveType_ConstantOfShapeSCHEMA_CUR();
extern void _PrimitiveType_CustomPredictSCHEMA_CUR();
extern void _PrimitiveType_PadFusionSCHEMA_CUR();
extern void _PrimitiveType_PriorBoxSCHEMA_CUR();
extern void _PrimitiveType_ZerosLikeSCHEMA_CUR();
extern void _PrimitiveType_DependSCHEMA_CUR();
extern void _PrimitiveType_UnsortedSegmentSumSCHEMA_CUR();
extern void _PrimitiveType_TensorListSetItemSCHEMA_CUR();
extern void _PrimitiveType_FillSCHEMA_CUR();
extern void _PrimitiveType_RankSCHEMA_CUR();
extern void _PrimitiveType_ClipSCHEMA_CUR();
extern void _PrimitiveType_SpaceToDepthSCHEMA_CUR();

void RegisterOps() {
  _PrimitiveType_MulFusionSCHEMA_CUR();
  _PrimitiveType_NonMaxSuppressionSCHEMA_CUR();
  _PrimitiveType_TensorListStackSCHEMA_CUR();
  _PrimitiveType_EltwiseSCHEMA_CUR();
  _PrimitiveType_AssignSCHEMA_CUR();
  _PrimitiveType_CropSCHEMA_CUR();
  _PrimitiveType_BatchNormSCHEMA_CUR();
  _PrimitiveType_NonZeroSCHEMA_CUR();
  _PrimitiveType_AddNSCHEMA_CUR();
  _PrimitiveType_MergeSCHEMA_CUR();
  _PrimitiveType_AbsSCHEMA_CUR();
  _PrimitiveType_CosSCHEMA_CUR();
  _PrimitiveType_SinSCHEMA_CUR();
  _PrimitiveType_LogSCHEMA_CUR();
  _PrimitiveType_NegSCHEMA_CUR();
  _PrimitiveType_NegGradSCHEMA_CUR();
  _PrimitiveType_LogGradSCHEMA_CUR();
  _PrimitiveType_SqrtSCHEMA_CUR();
  _PrimitiveType_SquareSCHEMA_CUR();
  _PrimitiveType_RsqrtSCHEMA_CUR();
  _PrimitiveType_LogicalNotSCHEMA_CUR();
  _PrimitiveType_FloorSCHEMA_CUR();
  _PrimitiveType_CeilSCHEMA_CUR();
  _PrimitiveType_RoundSCHEMA_CUR();
  _PrimitiveType_ReciprocalSCHEMA_CUR();
  _PrimitiveType_AssignAddSCHEMA_CUR();
  _PrimitiveType_UniqueSCHEMA_CUR();
  _PrimitiveType_IsFiniteSCHEMA_CUR();
  _PrimitiveType_TileFusionSCHEMA_CUR();
  _PrimitiveType_BinaryCrossEntropyGradSCHEMA_CUR();
  _PrimitiveType_StridedSliceSCHEMA_CUR();
  _PrimitiveType_L2NormalizeFusionSCHEMA_CUR();
  _PrimitiveType_RangeSCHEMA_CUR();
  _PrimitiveType_SizeSCHEMA_CUR();
  _PrimitiveType_CropAndResizeSCHEMA_CUR();
  _PrimitiveType_QuantDTypeCastSCHEMA_CUR();
  _PrimitiveType_InstanceNormSCHEMA_CUR();
  _PrimitiveType_AddFusionSCHEMA_CUR();
  _PrimitiveType_Conv2dTransposeFusionSCHEMA_CUR();
  _PrimitiveType_PowFusionSCHEMA_CUR();
  _PrimitiveType_ReverseV2SCHEMA_CUR();
  _PrimitiveType_BiasAddSCHEMA_CUR();
  _PrimitiveType_TensorListReserveSCHEMA_CUR();
  _PrimitiveType_SpliceSCHEMA_CUR();
  _PrimitiveType_MatMulSCHEMA_CUR();
  _PrimitiveType_ErfSCHEMA_CUR();
  _PrimitiveType_MinimumGradSCHEMA_CUR();
  _PrimitiveType_MaximumGradSCHEMA_CUR();
  _PrimitiveType_RealDivSCHEMA_CUR();
  _PrimitiveType_LogicalAndSCHEMA_CUR();
  _PrimitiveType_LogicalOrSCHEMA_CUR();
  _PrimitiveType_EqualSCHEMA_CUR();
  _PrimitiveType_NotEqualSCHEMA_CUR();
  _PrimitiveType_LessSCHEMA_CUR();
  _PrimitiveType_LessEqualSCHEMA_CUR();
  _PrimitiveType_GreaterSCHEMA_CUR();
  _PrimitiveType_GreaterEqualSCHEMA_CUR();
  _PrimitiveType_MaximumSCHEMA_CUR();
  _PrimitiveType_MinimumSCHEMA_CUR();
  _PrimitiveType_FloorDivSCHEMA_CUR();
  _PrimitiveType_FloorModSCHEMA_CUR();
  _PrimitiveType_ModSCHEMA_CUR();
  _PrimitiveType_SquaredDifferenceSCHEMA_CUR();
  _PrimitiveType_OneHotSCHEMA_CUR();
  _PrimitiveType_WhileSCHEMA_CUR();
  _PrimitiveType_ScatterNdSCHEMA_CUR();
  _PrimitiveType_DepthToSpaceSCHEMA_CUR();
  _PrimitiveType_GatherSCHEMA_CUR();
  _PrimitiveType_AssertSCHEMA_CUR();
  _PrimitiveType_InvertPermutationSCHEMA_CUR();
  _PrimitiveType_OnesLikeSCHEMA_CUR();
  _PrimitiveType_ConcatSCHEMA_CUR();
  _PrimitiveType_ScaleFusionSCHEMA_CUR();
  _PrimitiveType_HashtableLookupSCHEMA_CUR();
  _PrimitiveType_StackSCHEMA_CUR();
  _PrimitiveType_ShapeSCHEMA_CUR();
  _PrimitiveType_SparseToDenseSCHEMA_CUR();
  _PrimitiveType_TensorListFromTensorSCHEMA_CUR();
  _PrimitiveType_ReverseSequenceSCHEMA_CUR();
  _PrimitiveType_UnsqueezeSCHEMA_CUR();
  _PrimitiveType_FlattenSCHEMA_CUR();
  _PrimitiveType_ArgMinFusionSCHEMA_CUR();
  _PrimitiveType_SpaceToBatchSCHEMA_CUR();
  _PrimitiveType_UnstackSCHEMA_CUR();
  _PrimitiveType_BroadcastToSCHEMA_CUR();
  _PrimitiveType_SelectSCHEMA_CUR();
  _PrimitiveType_LinSpaceSCHEMA_CUR();
  _PrimitiveType_BiasAddGradSCHEMA_CUR();
  _PrimitiveType_LayerNormFusionSCHEMA_CUR();
  _PrimitiveType_EmbeddingLookupFusionSCHEMA_CUR();
  _PrimitiveType_CustomExtractFeaturesSCHEMA_CUR();
  _PrimitiveType_ResizeSCHEMA_CUR();
  _PrimitiveType_AdamSCHEMA_CUR();
  _PrimitiveType_ExpandDimsSCHEMA_CUR();
  _PrimitiveType_IfSCHEMA_CUR();
  _PrimitiveType_SoftmaxSCHEMA_CUR();
  _PrimitiveType_BatchToSpaceSCHEMA_CUR();
  _PrimitiveType_BatchToSpaceNDSCHEMA_CUR();
  _PrimitiveType_UniformRealSCHEMA_CUR();
  _PrimitiveType_DetectionPostProcessSCHEMA_CUR();
  _PrimitiveType_GatherNdSCHEMA_CUR();
  _PrimitiveType_GRUSCHEMA_CUR();
  _PrimitiveType_CustomNormalizeSCHEMA_CUR();
  _PrimitiveType_AdderFusionSCHEMA_CUR();
  _PrimitiveType_RandomStandardNormalSCHEMA_CUR();
  _PrimitiveType_FusedBatchNormSCHEMA_CUR();
  _PrimitiveType_AvgPoolFusionSCHEMA_CUR();
  _PrimitiveType_MaxPoolFusionSCHEMA_CUR();
  _PrimitiveType_ArgMaxFusionSCHEMA_CUR();
  _PrimitiveType_ExpFusionSCHEMA_CUR();
  _PrimitiveType_LayerNormGradSCHEMA_CUR();
  _PrimitiveType_AudioSpectrogramSCHEMA_CUR();
  _PrimitiveType_SpaceToBatchNDSCHEMA_CUR();
  _PrimitiveType_ROIPoolingSCHEMA_CUR();
  _PrimitiveType_PReLUFusionSCHEMA_CUR();
  _PrimitiveType_WhereSCHEMA_CUR();
  _PrimitiveType_SparseSoftmaxCrossEntropyWithLogitsSCHEMA_CUR();
  _PrimitiveType_PartialFusionSCHEMA_CUR();
  _PrimitiveType_SubFusionSCHEMA_CUR();
  _PrimitiveType_DivFusionSCHEMA_CUR();
  _PrimitiveType_MfccSCHEMA_CUR();
  _PrimitiveType_SplitSCHEMA_CUR();
  _PrimitiveType_ActivationSCHEMA_CUR();
  _PrimitiveType_TopKFusionSCHEMA_CUR();
  _PrimitiveType_CastSCHEMA_CUR();
  _PrimitiveType_StridedSliceGradSCHEMA_CUR();
  _PrimitiveType_SliceFusionSCHEMA_CUR();
  _PrimitiveType_TransposeSCHEMA_CUR();
  _PrimitiveType_ReduceFusionSCHEMA_CUR();
  _PrimitiveType_FullConnectionSCHEMA_CUR();
  _PrimitiveType_LshProjectionSCHEMA_CUR();
  _PrimitiveType_SkipGramSCHEMA_CUR();
  _PrimitiveType_SqueezeSCHEMA_CUR();
  _PrimitiveType_ActivationGradSCHEMA_CUR();
  _PrimitiveType_SwitchSCHEMA_CUR();
  _PrimitiveType_LSTMSCHEMA_CUR();
  _PrimitiveType_BinaryCrossEntropySCHEMA_CUR();
  _PrimitiveType_EluSCHEMA_CUR();
  _PrimitiveType_Conv2DFusionSCHEMA_CUR();
  _PrimitiveType_TensorListGetItemSCHEMA_CUR();
  _PrimitiveType_LRNSCHEMA_CUR();
  _PrimitiveType_ReshapeSCHEMA_CUR();
  _PrimitiveType_ConstantOfShapeSCHEMA_CUR();
  _PrimitiveType_CustomPredictSCHEMA_CUR();
  _PrimitiveType_PadFusionSCHEMA_CUR();
  _PrimitiveType_PriorBoxSCHEMA_CUR();
  _PrimitiveType_ZerosLikeSCHEMA_CUR();
  _PrimitiveType_DependSCHEMA_CUR();
  _PrimitiveType_UnsortedSegmentSumSCHEMA_CUR();
  _PrimitiveType_TensorListSetItemSCHEMA_CUR();
  _PrimitiveType_FillSCHEMA_CUR();
  _PrimitiveType_RankSCHEMA_CUR();
  _PrimitiveType_ClipSCHEMA_CUR();
  _PrimitiveType_SpaceToDepthSCHEMA_CUR();
}

#endif
}  // namespace lite
}  // namespace mindspore
