general:
    backend: mindspore
    parallel_search: True
    parallel_fully_train: True


pipeline: [nas, fully_train, benchmark_DIV2K, benchmark_Set5, benchmark_Set14, benchmark_BSDS100]


nas:
    pipe_step:
        type: SearchPipeStep

    dataset:
        type: DIV2K
        train:
            root_HR: /cache/datasets/DIV2K/div2k_train/hr
            root_LR: /cache/datasets/DIV2K/div2k_train/lr
            upscale: 2
            crop: 64
            hflip: true
            vflip: true
            rot90: true 
            shuffle: true
            batch_size: 16
            fixed_size: true
        test:
            root_HR: /cache/datasets/DIV2K/div2k_valid/hr
            root_LR: /cache/datasets/DIV2K/div2k_valid/lr
            upscale: 2
            fixed_size: true
            crop: 64

    search_space:
        type: SearchSpace
        modules: ['esrbody']
        esrbody:
            type: ESRN
            block_type: [S,G,C]
            conv_num: [4,6,8]
            growth_rate: [8,16,24,32]
            type_prob: [1,1,1]
            conv_prob: [1,1,1]
            growth_prob: [1,1,1,1]
            G0: 32
            scale: 2

    search_algorithm:
        type: ESRSearch
        codec: ESRCodec
        policy:
            num_generation: 20
            num_individual: 8
            num_elitism: 4 
            mutation_rate: 0.05
        range:
            node_num: 20
            min_active: 16
            max_params: 325000
            min_params: 315000

    trainer:
        type: Trainer
        callbacks: ESRTrainerCallback
        epochs: 500
        optimizer:
            type: Adam
            params:
                lr: 0.0001   # 0.001 for mindspore
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [100,200]
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: PSNR
            params:
                scale: 2 
                max_rgb: 255
        scale: 2
        cuda: True
        seed: 10


fully_train:
    pipe_step:
        type: TrainPipeStep
        models_folder: "{local_base_path}/output/nas/"
    dataset:
        ref: nas.dataset
    trainer:
        type: Trainer
        callbacks: ESRTrainerCallback
        node_num: 20
        epochs: 15000
        optimizer:
            type: Adam
            params:
                lr: 0.0001
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [8000,12000,13500,14500]
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: PSNR
            params:
                scale: 2 
                max_rgb: 255
        scale: 2
        seed: 10
        range:
            node_num: 20
    evaluator:
       type: Evaluator
       host_evaluator:
           type: HostEvaluator
           metric:
               type: PSNR


benchmark_DIV2K:
    pipe_step:
        type: BenchmarkPipeStep
        models_folder: "{local_base_path}/output/fully_train/"
    dataset:
        type: DIV2K
        test:
            root_HR: /cache/datasets/DIV2K/div2k_valid/hr
            root_LR: /cache/datasets/DIV2K/div2k_train/lr
            upscale: 2
    evaluator:
        type: Evaluator
        host_evaluator:
            type: HostEvaluator
            metric:
                type: PSNR
                params:
                    scale: 2 
                    max_rgb: 255
benchmark_Set5:
    pipe_step:
        type: BenchmarkPipeStep
        models_folder: "{local_base_path}/output/fully_train/"
    dataset:
        ref: benchmark_DIV2K.dataset
        type: Set5
        test:
            root_HR: /cache/datasets/DIV2K/Set5/hr
            root_LR: /cache/datasets/DIV2K/Set5/lr
    evaluator:
        ref: benchmark_DIV2K.evaluator

benchmark_Set14:
    pipe_step:
        type: BenchmarkPipeStep
        models_folder: "{local_base_path}/output/fully_train/"
    dataset:
        ref: benchmark_DIV2K.dataset
        type: Set14
        test:
            root_HR: /cache/datasets/DIV2K/Set14/hr
            root_LR: /cache/datasets/DIV2K/Set14/lr
    evaluator:
        ref: benchmark_DIV2K.evaluator

benchmark_BSDS100:
    pipe_step:
        type: BenchmarkPipeStep
        models_folder: "{local_base_path}/output/fully_train/"
    dataset:
        ref: benchmark_DIV2K.dataset
        type: BSDS100
        test:
            root_HR: /cache/datasets/DIV2K/BSDS100/hr
            root_LR: /cache/datasets/DIV2K/BSDS100/lr
    evaluator:
        ref: benchmark_DIV2K.evaluator
