/**
 * Copyright 2023 Huawei Technologies Co., Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef MINDSPORE_CORE_OPS_GEN_OPS_PRIMITIVE_H_
#define MINDSPORE_CORE_OPS_GEN_OPS_PRIMITIVE_H_

#include <memory>
#include "ir/anf.h"
#include "ir/primitive.h"
#include "ops/auto_generate/gen_ops_name.h"
#include "mindapi/base/macros.h"

namespace mindspore::prim {
GVAR_DEF(PrimitivePtr, kPrimAbsGrad, std::make_shared<Primitive>(ops::kNameAbsGrad))
GVAR_DEF(PrimitivePtr, kPrimAbs, std::make_shared<Primitive>(ops::kNameAbs))
GVAR_DEF(PrimitivePtr, kPrimACosGrad, std::make_shared<Primitive>(ops::kNameACosGrad))
GVAR_DEF(PrimitivePtr, kPrimAcos, std::make_shared<Primitive>(ops::kNameAcos))
GVAR_DEF(PrimitivePtr, kPrimAcoshGrad, std::make_shared<Primitive>(ops::kNameAcoshGrad))
GVAR_DEF(PrimitivePtr, kPrimAcosh, std::make_shared<Primitive>(ops::kNameAcosh))
GVAR_DEF(PrimitivePtr, kPrimAdd, std::make_shared<Primitive>(ops::kNameAdd))
GVAR_DEF(PrimitivePtr, kPrimAddcdiv, std::make_shared<Primitive>(ops::kNameAddcdiv))
GVAR_DEF(PrimitivePtr, kPrimAddcmul, std::make_shared<Primitive>(ops::kNameAddcmul))
GVAR_DEF(PrimitivePtr, kPrimAngle, std::make_shared<Primitive>(ops::kNameAngle))
GVAR_DEF(PrimitivePtr, kPrimArgmax, std::make_shared<Primitive>(ops::kNameArgmax))
GVAR_DEF(PrimitivePtr, kPrimAsinGrad, std::make_shared<Primitive>(ops::kNameAsinGrad))
GVAR_DEF(PrimitivePtr, kPrimAsin, std::make_shared<Primitive>(ops::kNameAsin))
GVAR_DEF(PrimitivePtr, kPrimAsinhGrad, std::make_shared<Primitive>(ops::kNameAsinhGrad))
GVAR_DEF(PrimitivePtr, kPrimAsinh, std::make_shared<Primitive>(ops::kNameAsinh))
GVAR_DEF(PrimitivePtr, kPrimAssign, std::make_shared<Primitive>(ops::kNameAssign))
GVAR_DEF(PrimitivePtr, kPrimAtan2, std::make_shared<Primitive>(ops::kNameAtan2))
GVAR_DEF(PrimitivePtr, kPrimAtanGrad, std::make_shared<Primitive>(ops::kNameAtanGrad))
GVAR_DEF(PrimitivePtr, kPrimAtan, std::make_shared<Primitive>(ops::kNameAtan))
GVAR_DEF(PrimitivePtr, kPrimAtanh, std::make_shared<Primitive>(ops::kNameAtanh))
GVAR_DEF(PrimitivePtr, kPrimAvgPoolGrad, std::make_shared<Primitive>(ops::kNameAvgPoolGrad))
GVAR_DEF(PrimitivePtr, kPrimAvgPool, std::make_shared<Primitive>(ops::kNameAvgPool))
GVAR_DEF(PrimitivePtr, kPrimBaddbmm, std::make_shared<Primitive>(ops::kNameBaddbmm))
GVAR_DEF(PrimitivePtr, kPrimBatchNormGradGrad, std::make_shared<Primitive>(ops::kNameBatchNormGradGrad))
GVAR_DEF(PrimitivePtr, kPrimBatchNormGrad, std::make_shared<Primitive>(ops::kNameBatchNormGrad))
GVAR_DEF(PrimitivePtr, kPrimBetainc, std::make_shared<Primitive>(ops::kNameBetainc))
GVAR_DEF(PrimitivePtr, kPrimBiasAddGrad, std::make_shared<Primitive>(ops::kNameBiasAddGrad))
GVAR_DEF(PrimitivePtr, kPrimBiasAdd, std::make_shared<Primitive>(ops::kNameBiasAdd))
GVAR_DEF(PrimitivePtr, kPrimBoolNot, std::make_shared<Primitive>(ops::kNameBoolNot))
GVAR_DEF(PrimitivePtr, kPrimCeil, std::make_shared<Primitive>(ops::kNameCeil))
GVAR_DEF(PrimitivePtr, kPrimCeLU, std::make_shared<Primitive>(ops::kNameCeLU))
GVAR_DEF(PrimitivePtr, kPrimCholeskyGrad, std::make_shared<Primitive>(ops::kNameCholeskyGrad))
GVAR_DEF(PrimitivePtr, kPrimCholeskyInverse, std::make_shared<Primitive>(ops::kNameCholeskyInverse))
GVAR_DEF(PrimitivePtr, kPrimCholesky, std::make_shared<Primitive>(ops::kNameCholesky))
GVAR_DEF(PrimitivePtr, kPrimComplex, std::make_shared<Primitive>(ops::kNameComplex))
GVAR_DEF(PrimitivePtr, kPrimConj, std::make_shared<Primitive>(ops::kNameConj))
GVAR_DEF(PrimitivePtr, kPrimCos, std::make_shared<Primitive>(ops::kNameCos))
GVAR_DEF(PrimitivePtr, kPrimCosh, std::make_shared<Primitive>(ops::kNameCosh))
GVAR_DEF(PrimitivePtr, kPrimDiag, std::make_shared<Primitive>(ops::kNameDiag))
GVAR_DEF(PrimitivePtr, kPrimEig, std::make_shared<Primitive>(ops::kNameEig))
GVAR_DEF(PrimitivePtr, kPrimEluGrad, std::make_shared<Primitive>(ops::kNameEluGrad))
GVAR_DEF(PrimitivePtr, kPrimElu, std::make_shared<Primitive>(ops::kNameElu))
GVAR_DEF(PrimitivePtr, kPrimEqual, std::make_shared<Primitive>(ops::kNameEqual))
GVAR_DEF(PrimitivePtr, kPrimErf, std::make_shared<Primitive>(ops::kNameErf))
GVAR_DEF(PrimitivePtr, kPrimErfc, std::make_shared<Primitive>(ops::kNameErfc))
GVAR_DEF(PrimitivePtr, kPrimErfinv, std::make_shared<Primitive>(ops::kNameErfinv))
GVAR_DEF(PrimitivePtr, kPrimExp, std::make_shared<Primitive>(ops::kNameExp))
GVAR_DEF(PrimitivePtr, kPrimExpandDims, std::make_shared<Primitive>(ops::kNameExpandDims))
GVAR_DEF(PrimitivePtr, kPrimExpm1, std::make_shared<Primitive>(ops::kNameExpm1))
GVAR_DEF(PrimitivePtr, kPrimEye, std::make_shared<Primitive>(ops::kNameEye))
GVAR_DEF(PrimitivePtr, kPrimFastGeLUGrad, std::make_shared<Primitive>(ops::kNameFastGeLUGrad))
GVAR_DEF(PrimitivePtr, kPrimFastGeLU, std::make_shared<Primitive>(ops::kNameFastGeLU))
GVAR_DEF(PrimitivePtr, kPrimFFTWithSize, std::make_shared<Primitive>(ops::kNameFFTWithSize))
GVAR_DEF(PrimitivePtr, kPrimFlatten, std::make_shared<Primitive>(ops::kNameFlatten))
GVAR_DEF(PrimitivePtr, kPrimFloorDiv, std::make_shared<Primitive>(ops::kNameFloorDiv))
GVAR_DEF(PrimitivePtr, kPrimFloorMod, std::make_shared<Primitive>(ops::kNameFloorMod))
GVAR_DEF(PrimitivePtr, kPrimFloor, std::make_shared<Primitive>(ops::kNameFloor))
GVAR_DEF(PrimitivePtr, kPrimGatherDGradV2, std::make_shared<Primitive>(ops::kNameGatherDGradV2))
GVAR_DEF(PrimitivePtr, kPrimGatherD, std::make_shared<Primitive>(ops::kNameGatherD))
GVAR_DEF(PrimitivePtr, kPrimGatherNd, std::make_shared<Primitive>(ops::kNameGatherNd))
GVAR_DEF(PrimitivePtr, kPrimGather, std::make_shared<Primitive>(ops::kNameGather))
GVAR_DEF(PrimitivePtr, kPrimGcd, std::make_shared<Primitive>(ops::kNameGcd))
GVAR_DEF(PrimitivePtr, kPrimGeLUGrad, std::make_shared<Primitive>(ops::kNameGeLUGrad))
GVAR_DEF(PrimitivePtr, kPrimGeLU, std::make_shared<Primitive>(ops::kNameGeLU))
GVAR_DEF(PrimitivePtr, kPrimGeqrf, std::make_shared<Primitive>(ops::kNameGeqrf))
GVAR_DEF(PrimitivePtr, kPrimGreaterEqual, std::make_shared<Primitive>(ops::kNameGreaterEqual))
GVAR_DEF(PrimitivePtr, kPrimGreater, std::make_shared<Primitive>(ops::kNameGreater))
GVAR_DEF(PrimitivePtr, kPrimGridSampler2DGrad, std::make_shared<Primitive>(ops::kNameGridSampler2DGrad))
GVAR_DEF(PrimitivePtr, kPrimGridSampler2D, std::make_shared<Primitive>(ops::kNameGridSampler2D))
GVAR_DEF(PrimitivePtr, kPrimGridSampler3DGrad, std::make_shared<Primitive>(ops::kNameGridSampler3DGrad))
GVAR_DEF(PrimitivePtr, kPrimGridSampler3D, std::make_shared<Primitive>(ops::kNameGridSampler3D))
GVAR_DEF(PrimitivePtr, kPrimLinSpace, std::make_shared<Primitive>(ops::kNameLinSpace))
GVAR_DEF(PrimitivePtr, kPrimLog1p, std::make_shared<Primitive>(ops::kNameLog1p))
GVAR_DEF(PrimitivePtr, kPrimLogMatrixDeterminant, std::make_shared<Primitive>(ops::kNameLogMatrixDeterminant))
GVAR_DEF(PrimitivePtr, kPrimLog, std::make_shared<Primitive>(ops::kNameLog))
GVAR_DEF(PrimitivePtr, kPrimLogSoftmaxGrad, std::make_shared<Primitive>(ops::kNameLogSoftmaxGrad))
GVAR_DEF(PrimitivePtr, kPrimLogSoftmax, std::make_shared<Primitive>(ops::kNameLogSoftmax))
GVAR_DEF(PrimitivePtr, kPrimLogicalAnd, std::make_shared<Primitive>(ops::kNameLogicalAnd))
GVAR_DEF(PrimitivePtr, kPrimLogicalNot, std::make_shared<Primitive>(ops::kNameLogicalNot))
GVAR_DEF(PrimitivePtr, kPrimLogicalOr, std::make_shared<Primitive>(ops::kNameLogicalOr))
GVAR_DEF(PrimitivePtr, kPrimLogicalXor, std::make_shared<Primitive>(ops::kNameLogicalXor))
GVAR_DEF(PrimitivePtr, kPrimLogitGrad, std::make_shared<Primitive>(ops::kNameLogitGrad))
GVAR_DEF(PrimitivePtr, kPrimLogit, std::make_shared<Primitive>(ops::kNameLogit))
GVAR_DEF(PrimitivePtr, kPrimMatrixDeterminant, std::make_shared<Primitive>(ops::kNameMatrixDeterminant))
GVAR_DEF(PrimitivePtr, kPrimMatrixExp, std::make_shared<Primitive>(ops::kNameMatrixExp))
GVAR_DEF(PrimitivePtr, kPrimNanToNum, std::make_shared<Primitive>(ops::kNameNanToNum))
GVAR_DEF(PrimitivePtr, kPrimNeg, std::make_shared<Primitive>(ops::kNameNeg))
GVAR_DEF(PrimitivePtr, kPrimNextAfter, std::make_shared<Primitive>(ops::kNameNextAfter))
GVAR_DEF(PrimitivePtr, kPrimNLLLossGrad, std::make_shared<Primitive>(ops::kNameNLLLossGrad))
GVAR_DEF(PrimitivePtr, kPrimNLLLoss, std::make_shared<Primitive>(ops::kNameNLLLoss))
GVAR_DEF(PrimitivePtr, kPrimNonZero, std::make_shared<Primitive>(ops::kNameNonZero))
GVAR_DEF(PrimitivePtr, kPrimNotEqual, std::make_shared<Primitive>(ops::kNameNotEqual))
GVAR_DEF(PrimitivePtr, kPrimOneHot, std::make_shared<Primitive>(ops::kNameOneHot))
GVAR_DEF(PrimitivePtr, kPrimOnesLike, std::make_shared<Primitive>(ops::kNameOnesLike))
GVAR_DEF(PrimitivePtr, kPrimPow, std::make_shared<Primitive>(ops::kNamePow))
GVAR_DEF(PrimitivePtr, kPrimPReLUGrad, std::make_shared<Primitive>(ops::kNamePReLUGrad))
GVAR_DEF(PrimitivePtr, kPrimPReLU, std::make_shared<Primitive>(ops::kNamePReLU))
GVAR_DEF(PrimitivePtr, kPrimQr, std::make_shared<Primitive>(ops::kNameQr))
GVAR_DEF(PrimitivePtr, kPrimRandpermV2, std::make_shared<Primitive>(ops::kNameRandpermV2))
GVAR_DEF(PrimitivePtr, kPrimRange, std::make_shared<Primitive>(ops::kNameRange))
GVAR_DEF(PrimitivePtr, kPrimRank, std::make_shared<Primitive>(ops::kNameRank))
GVAR_DEF(PrimitivePtr, kPrimRealDiv, std::make_shared<Primitive>(ops::kNameRealDiv))
GVAR_DEF(PrimitivePtr, kPrimReal, std::make_shared<Primitive>(ops::kNameReal))
GVAR_DEF(PrimitivePtr, kPrimReciprocalGrad, std::make_shared<Primitive>(ops::kNameReciprocalGrad))
GVAR_DEF(PrimitivePtr, kPrimReciprocal, std::make_shared<Primitive>(ops::kNameReciprocal))
GVAR_DEF(PrimitivePtr, kPrimReduceAll, std::make_shared<Primitive>(ops::kNameReduceAll))
GVAR_DEF(PrimitivePtr, kPrimReduceAny, std::make_shared<Primitive>(ops::kNameReduceAny))
GVAR_DEF(PrimitivePtr, kPrimReduceMax, std::make_shared<Primitive>(ops::kNameReduceMax))
GVAR_DEF(PrimitivePtr, kPrimReduceMean, std::make_shared<Primitive>(ops::kNameReduceMean))
GVAR_DEF(PrimitivePtr, kPrimReduceMin, std::make_shared<Primitive>(ops::kNameReduceMin))
GVAR_DEF(PrimitivePtr, kPrimReduceProd, std::make_shared<Primitive>(ops::kNameReduceProd))
GVAR_DEF(PrimitivePtr, kPrimReduceStd, std::make_shared<Primitive>(ops::kNameReduceStd))
GVAR_DEF(PrimitivePtr, kPrimReduceSum, std::make_shared<Primitive>(ops::kNameReduceSum))
GVAR_DEF(PrimitivePtr, kPrimReLU6Grad, std::make_shared<Primitive>(ops::kNameReLU6Grad))
GVAR_DEF(PrimitivePtr, kPrimReLU6, std::make_shared<Primitive>(ops::kNameReLU6))
GVAR_DEF(PrimitivePtr, kPrimReluGrad, std::make_shared<Primitive>(ops::kNameReluGrad))
GVAR_DEF(PrimitivePtr, kPrimReLU, std::make_shared<Primitive>(ops::kNameReLU))
GVAR_DEF(PrimitivePtr, kPrimReshape, std::make_shared<Primitive>(ops::kNameReshape))
GVAR_DEF(PrimitivePtr, kPrimResizeBicubicGrad, std::make_shared<Primitive>(ops::kNameResizeBicubicGrad))
GVAR_DEF(PrimitivePtr, kPrimResizeBicubic, std::make_shared<Primitive>(ops::kNameResizeBicubic))
GVAR_DEF(PrimitivePtr, kPrimResizeBilinearGrad, std::make_shared<Primitive>(ops::kNameResizeBilinearGrad))
GVAR_DEF(PrimitivePtr, kPrimResizeBilinearV2, std::make_shared<Primitive>(ops::kNameResizeBilinearV2))
GVAR_DEF(PrimitivePtr, kPrimResizeLinear1DGrad, std::make_shared<Primitive>(ops::kNameResizeLinear1DGrad))
GVAR_DEF(PrimitivePtr, kPrimResizeLinear1D, std::make_shared<Primitive>(ops::kNameResizeLinear1D))
GVAR_DEF(PrimitivePtr, kPrimResizeNearestNeighborV2Grad,
         std::make_shared<Primitive>(ops::kNameResizeNearestNeighborV2Grad))
GVAR_DEF(PrimitivePtr, kPrimResizeNearestNeighborV2, std::make_shared<Primitive>(ops::kNameResizeNearestNeighborV2))
GVAR_DEF(PrimitivePtr, kPrimReverseV2, std::make_shared<Primitive>(ops::kNameReverseV2))
GVAR_DEF(PrimitivePtr, kPrimRightShift, std::make_shared<Primitive>(ops::kNameRightShift))
GVAR_DEF(PrimitivePtr, kPrimRoll, std::make_shared<Primitive>(ops::kNameRoll))
GVAR_DEF(PrimitivePtr, kPrimRound, std::make_shared<Primitive>(ops::kNameRound))
GVAR_DEF(PrimitivePtr, kPrimRsqrtGrad, std::make_shared<Primitive>(ops::kNameRsqrtGrad))
GVAR_DEF(PrimitivePtr, kPrimRsqrt, std::make_shared<Primitive>(ops::kNameRsqrt))
GVAR_DEF(PrimitivePtr, kPrimScatterNd, std::make_shared<Primitive>(ops::kNameScatterNd))
GVAR_DEF(PrimitivePtr, kPrimSigmoidGrad, std::make_shared<Primitive>(ops::kNameSigmoidGrad))
GVAR_DEF(PrimitivePtr, kPrimSigmoid, std::make_shared<Primitive>(ops::kNameSigmoid))
GVAR_DEF(PrimitivePtr, kPrimSin, std::make_shared<Primitive>(ops::kNameSin))
GVAR_DEF(PrimitivePtr, kPrimSinc, std::make_shared<Primitive>(ops::kNameSinc))
GVAR_DEF(PrimitivePtr, kPrimSinh, std::make_shared<Primitive>(ops::kNameSinh))
GVAR_DEF(PrimitivePtr, kPrimSqrtGrad, std::make_shared<Primitive>(ops::kNameSqrtGrad))
GVAR_DEF(PrimitivePtr, kPrimSqrt, std::make_shared<Primitive>(ops::kNameSqrt))
GVAR_DEF(PrimitivePtr, kPrimSquare, std::make_shared<Primitive>(ops::kNameSquare))
GVAR_DEF(PrimitivePtr, kPrimTensorCopySlices, std::make_shared<Primitive>(ops::kNameTensorCopySlices))
GVAR_DEF(PrimitivePtr, kPrimTensorShape, std::make_shared<Primitive>(ops::kNameTensorShape))
GVAR_DEF(PrimitivePtr, kPrimTrace, std::make_shared<Primitive>(ops::kNameTrace))
GVAR_DEF(PrimitivePtr, kPrimTranspose, std::make_shared<Primitive>(ops::kNameTranspose))
GVAR_DEF(PrimitivePtr, kPrimZerosLike, std::make_shared<Primitive>(ops::kNameZerosLike))
GVAR_DEF(PrimitivePtr, kPrimExtractImagePatches, std::make_shared<Primitive>(ops::kNameExtractImagePatches))
}  // namespace mindspore::prim
#endif  // MINDSPORE_CORE_OPS_GEN_OPS_PRIMITIVE_H_
