from tests.st.compiler.control.inner.test_000_single_if import *
from tests.st.compiler.control.inner.test_001_single_while import *
from tests.st.compiler.control.inner.test_002_single_for import *
from tests.st.compiler.control.inner.test_010_if_in_if import *
from tests.st.compiler.control.inner.test_011_if_in_while import *
from tests.st.compiler.control.inner.test_011_if_in_while_break import *
from tests.st.compiler.control.inner.test_012_if_in_for import *
from tests.st.compiler.control.inner.test_012_if_in_for_break import *
from tests.st.compiler.control.inner.test_020_while_in_if import *
from tests.st.compiler.control.inner.test_021_while_while_normal import *
from tests.st.compiler.control.inner.test_022_for_while_normal import *
from tests.st.compiler.control.inner.test_030_for_in_if import *
from tests.st.compiler.control.inner.test_031_for_in_while import *
from tests.st.compiler.control.inner.test_032_for_in_for import *
from tests.st.compiler.control.inner.test_100_if_after_if import *
from tests.st.compiler.control.inner.test_101_if_after_while import *
from tests.st.compiler.control.inner.test_102_if_after_for import *
from tests.st.compiler.control.inner.test_110_if_after_if_in_if import *
from tests.st.compiler.control.inner.test_111_if_after_if_in_while import *
from tests.st.compiler.control.inner.test_112_if_after_if_in_for import *
from tests.st.compiler.control.inner.test_120_if_after_while_in_if import *
from tests.st.compiler.control.inner.test_121_if_after_while_in_while import *
from tests.st.compiler.control.inner.test_122_if_after_while_in_for import *
from tests.st.compiler.control.inner.test_130_if_after_for_in_if import *
from tests.st.compiler.control.inner.test_131_if_after_for_in_while import *
from tests.st.compiler.control.inner.test_132_if_after_for_in_for import *
from tests.st.compiler.control.inner.test_200_while_after_if import *
from tests.st.compiler.control.inner.test_201_for_n_while import *
from tests.st.compiler.control.inner.test_202_while_n_while import *
from tests.st.compiler.control.inner.test_210_while_after_if_in_if import *
from tests.st.compiler.control.inner.test_211_while_after_if_in_while import *
from tests.st.compiler.control.inner.test_212_while_after_if_in_for import *
from tests.st.compiler.control.inner.test_220_while_after_while_in_if import *
from tests.st.compiler.control.inner.test_221_while_while_while import *
from tests.st.compiler.control.inner.test_222_for_while_while import *
from tests.st.compiler.control.inner.test_230_while_after_for_in_if import *
from tests.st.compiler.control.inner.test_231_while_for_while import *
from tests.st.compiler.control.inner.test_232_for_for_while import *
from tests.st.compiler.control.inner.test_300_for_after_if import *
from tests.st.compiler.control.inner.test_301_while_normal_for import *
from tests.st.compiler.control.inner.test_302_for_after_for import *
from tests.st.compiler.control.inner.test_310_for_after_if_in_if import *
from tests.st.compiler.control.inner.test_311_while_if_for import *
from tests.st.compiler.control.inner.test_320_for_after_while_in_if import *
from tests.st.compiler.control.inner.test_321_while_while_in_while import *
from tests.st.compiler.control.inner.test_322_for_after_while_in_for import *
from tests.st.compiler.control.inner.test_330_for_after_for_in_if import *
from tests.st.compiler.control.inner.test_331_for_after_for_in_while import *
from tests.st.compiler.control.inner.test_332_for_after_for_in_for import *
from tests.st.compiler.control.inner.test_break_continue import *
from tests.st.compiler.control.test_abstract_funcgraph import *
from tests.st.compiler.control.test_all_control_cases import *
from tests.st.compiler.control.test_ascend_control_sink import *
from tests.st.compiler.control.test_call_tuple_transform import *
from tests.st.compiler.control.test_check_for_body_get_outer_class_attr_log import *
from tests.st.compiler.control.test_complex_for_if_core_dump import *
from tests.st.compiler.control.test_control_flow_for_mindrt import *
from tests.st.compiler.control.test_control_flow_infer import *
from tests.st.compiler.control.test_control_flow_specialize import *
from tests.st.compiler.control.test_control_tuple_getitem_err import *
from tests.st.compiler.control.test_cont_break import *
from tests.st.compiler.control.test_cont_grad import *
from tests.st.compiler.control.test_dde_error_log import *
from tests.st.compiler.control.test_for_half_unroll import *
from tests.st.compiler.control.test_for_in_for_break_phi_eliminate import *
from tests.st.compiler.control.test_for_to_while import *
from tests.st.compiler.control.test_fun_fun import *
from tests.st.compiler.control.test_high_order_control import *
from tests.st.compiler.control.test_if_by_if import *
from tests.st.compiler.control.test_if_mindir import *
from tests.st.compiler.control.test_multigraph_sink import *
from tests.st.compiler.control.test_parallel_if import *
from tests.st.compiler.control.test_partial_eliminate import *
from tests.st.compiler.control.test_recrusive_fun import *
from tests.st.compiler.control.test_recrusive_mindir import *
from tests.st.compiler.control.test_switch_layer import *
from tests.st.compiler.control.test_switch_layer_mindir import *
from tests.st.compiler.control.test_switch_simplify import *
from tests.st.compiler.control.test_tensor_in_list import *
from tests.st.compiler.control.test_while import *
from tests.st.compiler.control.test_while_grad import *
from tests.st.compiler.control.test_while_mindir import *
